// Harbor source for Azora Manga
const BASE="https://azorafly.com"; const PAGE_SIZE=48;
function clean(t){return t?String(t).replace(/\s+/g," ").trim():"";}
function abs(u){if(!u)return undefined;u=String(u).trim();if(!u||u.startsWith("data:"))return undefined;if(/^https?:\/\//i.test(u))return u;if(u.startsWith("//"))return "https:"+u;if(u.startsWith("/"))return BASE+u;return BASE+"/"+u;}
async function getDoc(path){const r=await harbor.http(BASE+path,{responseType:"text",timeoutMs:30000,headers:{Referer:BASE+"/","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0.0.0 Safari/537.36"}});if(!r.ok)throw new Error("http "+r.status+" for "+path);return harbor.parseHtml(r.body||"");}
function firstText(el,sels){for(const s of sels){const x=el?.querySelector(s),t=clean(x?.text());if(t)return t;}return undefined;}
function imageFrom(el){const x=el?.querySelector("img");if(!x)return undefined;return abs(x.attr("data-src")||x.attr("data-lazy-src")||x.attr("data-original")||x.attr("src"));}
function firstAttr(el,sels,attrs){for(const s of sels){const x=el?.querySelector(s);if(!x)continue;for(const a of attrs){const v=x.attr(a);if(v)return v;}}return undefined;}
function mangaId(h){const m=String(h||"").replace(/^https?:\/\/[^/]+/i,"").match(/^\/series\/([^/?#]+)\/?/i);return m?decodeURIComponent(m[1]):null;}
function card(el){const a=el.querySelector("a[href^='/series/']")||el.querySelector("a[href*='/series/']");if(!a)return null;const id=mangaId(a.attr("href"));if(!id)return null;const title=clean(firstText(el,["h3","h2","h1","[class*='title']"])||el.querySelector("img")?.attr("alt")||a.attr("aria-label")||a.text());if(!title)return null;return{id,title,cover:imageFrom(el)};}
function cards(doc){const out=[],seen=new Set();for(const sel of ["div[class*='card']","article","div.relative.overflow-hidden"]){for(const el of doc.querySelectorAll(sel)){const x=card(el);if(x&&!seen.has(x.id)){seen.add(x.id);out.push(x);}}if(out.length)return out;}return out;}
function chapterNumber(text,href){const s=clean(text),h=String(href||"");let m=s.match(/(?:الفصل|chapter|ch\.?|فصل)\s*#?\s*([0-9]+(?:\.[0-9]+)?)/i);if(!m)m=h.match(/\/chapter\/?([0-9]+(?:\.[0-9]+)?)/i);if(!m)m=h.match(/\/series\/[^/]+\/([0-9]+(?:\.[0-9]+)?)(?:[/?#]|$)/i);return m?m[1]:null;}
function chapter(a){const href=abs(a.attr("href")||""),raw=a.attr("href")||"";if(!href||!/\/chapter(?:\/|\?|#|$)/i.test(raw)&&!/\/series\/[^/]+\/[^/]+/i.test(raw))return null;const n=a.attr("data-number")||chapterNumber(a.text(),raw);if(!n)return null;return{id:href,chapter:n,title:clean(a.text())||"الفصل "+n,volume:null,pages:0,language:"ar"};}
function chapters(doc){const out=[],seen=new Set();for(const a of doc.querySelectorAll("a[href*='/chapter'],a[href*='/series/']")){const c=chapter(a);if(c&&!seen.has(c.id)){seen.add(c.id);out.push(c);}}out.sort((a,b)=>parseFloat(b.chapter)-parseFloat(a.chapter));return out;}
const plugin={
 id:"azora",name:"Azora Manga",
 async popular(offset,tagId){let p=Math.floor(offset/PAGE_SIZE)+1,path="/series?sort=popular&page="+p;if(tagId)path+="&genre="+encodeURIComponent(tagId);return cards(await getDoc(path));},
 async search(query,offset,tagId){let p=Math.floor(offset/PAGE_SIZE)+1,path="/series?searchTerm="+encodeURIComponent(query)+"&page="+p;if(tagId)path+="&genre="+encodeURIComponent(tagId);return cards(await getDoc(path));},
 async detail(id){const doc=await getDoc("/series/"+encodeURIComponent(id)),root=doc.querySelector("main")||doc;return{id,title:clean(root.querySelector("h1")?.text())||id,cover:imageFrom(root.querySelector("img[src*='upload']")?.parentElement||root.querySelector("img[src*='storage']")?.parentElement||root),altTitle:firstText(root,["[class*='alternative']"]),author:firstText(root,["[class*='author']","span:contains('المؤلف')","div:contains('المؤلف')"]),status:firstText(root,["[class*='status']","span:contains('مستمر')","span:contains('مكتمل')"]),description:firstAttr(root,["meta[property='og:description']","meta[name='description']"],["content"])||firstText(root,["[class*='description']"]),lastChapter:firstText(root,["a[href*='/chapter']"])};},
 async chapters(id){return chapters(await getDoc("/series/"+encodeURIComponent(id)));},
 async pageUrls(chapterId){const path="/"+String(chapterId).replace(/^https?:\/\/[^/]+/i,"").replace(/^\//,""),doc=await getDoc(path),urls=[],seen=new Set();for(const sel of ["img[src*='storage.azorafly.com']","img[data-src*='storage.azorafly.com']","img[src*='/upload/']","img[data-src*='/upload/']","main img","article img"]){for(const img of doc.querySelectorAll(sel)){const u=abs(img.attr("data-src")||img.attr("data-lazy-src")||img.attr("data-original")||img.attr("src"));if(u&&!seen.has(u)){seen.add(u);urls.push(u);}}if(urls.length)break;}return urls;},
 async tags(){return[];}
};
return plugin;
