const BASE = "https://mangalik.net";
const PAGE_SIZE = 48;
function clean(v){return v?String(v).replace(/\s+/g," ").trim():"";}
function abs(u){if(!u)return undefined;u=String(u).trim();if(/^https?:\/\//i.test(u))return u;if(u.startsWith("//"))return "https:"+u;if(u.startsWith("/"))return BASE+u;return BASE+"/"+u;}
function pathOf(u){const x=abs(u);return x?x.replace(/^https?:\/\/[^/]+/i,""):"";}
async function get(path){const r=await harbor.http(BASE+path,{responseType:"text"});if(!r.ok)throw new Error("HTTP "+r.status);return harbor.parseHtml(r.body||"");}
function mangaId(h){const m=pathOf(h).match(/^\/manga\/([^/?#]+)\/?$/i);return m?decodeURIComponent(m[1]):null;}
function summary(a){const id=mangaId(a.attr("href")||"");if(!id)return null;let p=a,title=clean(a.attr("title"))||clean(a.text()),cover;for(let i=0;i<8&&p;i++,p=p.parentElement){if(!title)title=clean(p.querySelector(".post-title")?.text())||clean(p.querySelector("h2")?.text())||clean(p.querySelector("h3")?.text());if(!cover){const img=p.querySelector("img");cover=abs(img?.attr("data-src")||img?.attr("data-lazy-src")||img?.attr("data-original")||img?.attr("src"));}if(title&&cover)break;}return{id,title:title||id.replace(/[-_]+/g," "),cover};}
function collect(doc,selectors){const out=[],seen=new Set();for(const s of selectors)for(const a of doc.querySelectorAll(s)){const x=summary(a);if(x&&!seen.has(x.id)){seen.add(x.id);out.push(x);}}return out;}
function chapter(a){const href=abs(a.attr("href")||""),m=pathOf(href).match(/^\/manga\/([^/?#]+)\/([^/?#]+)\/?$/i);if(!m)return null;const text=clean(a.text())||clean(a.attr("title"))||m[2],n=a.attr("data-number")||(text.match(/(?:chapter|ch\.?|الفصل|فصل)\s*#?\s*([0-9]+(?:\.[0-9]+)?)/i)||[])[1]||(m[2].match(/([0-9]+(?:\.[0-9]+)?)/)||[])[1]||m[2];return{id:href,chapter:n,title:text||"Chapter "+n,volume:null,pages:0,language:"ar"};}
const plugin={
 id:"mangalik",name:"مانجا ليك",
 async popular(offset){const page=Math.floor(offset/PAGE_SIZE)+1;for(const p of(page===1?["/","/manga/"]:["/page/"+page+"/","/manga/page/"+page+"/"])){try{const r=collect(await get(p),["a[href^='/manga/']","a[href*='mangalik.net/manga/']"]);if(r.length)return r;}catch(_){}}return[];},
 async search(query,offset){const q=clean(query);if(!q)return[];const e=encodeURIComponent(q),page=Math.floor(offset/PAGE_SIZE)+1;const urls=page===1?["/?post_type=wp-manga&s="+e,"/manga/?post_type=wp-manga&s="+e,"/?s="+e]:["/?post_type=wp-manga&s="+e+"&paged="+page,"/manga/?post_type=wp-manga&s="+e+"&paged="+page,"/?s="+e+"&paged="+page];for(const u of urls){try{const doc=await get(u);const r=collect(doc,[".c-tabs-item__content .post-title a[href]",".c-tabs-item__content a[href^='/manga/']",".row.c-tabs-item__content a[href]",".tab-summary .post-title a[href]",".item-summary .post-title a[href]","a[href^='/manga/']","a[href*='mangalik.net/manga/']"]);if(r.length)return r;}catch(_){}}return[];},
 async detail(id){const doc=await get("/manga/"+encodeURIComponent(id)+"/");const title=clean(doc.querySelector("h1")?.text())||id,img=doc.querySelector(".summary_image img")||doc.querySelector(".profile-manga img");return{id,title,cover:abs(img?.attr("data-src")||img?.attr("data-lazy-src")||img?.attr("data-original")||img?.attr("src")),description:clean(doc.querySelector(".description-summary")?.text())||clean(doc.querySelector(".summary__content")?.text()),status:clean(doc.querySelector(".manga-status .summary-content")?.text()),author:clean(doc.querySelector(".manga-authors .summary-content")?.text())};},
 async chapters(id){const doc=await get("/manga/"+encodeURIComponent(id)+"/");let out=[],seen=new Set();for(const s of[".wp-manga-chapter a[href]",".listing-chapters_wrap a[href]",".version-chap a[href]",".c-tabs-item__content a[href]"]){for(const a of doc.querySelectorAll(s)){const c=chapter(a);if(c&&!seen.has(c.id)){seen.add(c.id);out.push(c);}}if(out.length)break;}out.sort((a,b)=>parseFloat(b.chapter)-parseFloat(a.chapter));return out;},
 async pageUrls(chapterId){const doc=await get(pathOf(chapterId)),out=[],seen=new Set();for(const s of[".reading-content img",".page-break img",".wp-manga-chapter-img img",".entry-content img"]){for(const img of doc.querySelectorAll(s)){const u=abs(img.attr("data-src")||img.attr("data-lazy-src")||img.attr("data-original")||img.attr("src"));if(u&&!seen.has(u)){seen.add(u);out.push(u);}}if(out.length)break;}return out;}
};
return plugin;